export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const INITIATE_LOGOUT = 'INITIATE_LOGOUT';
export const GET_ROLE = "GET_ROLE";

export const ADD_ROLE = 'ADD_ROLE';

export const ADD_DRAWING = 'ADD_DRAWING';

export const DAILY_REPORT = 'DAILY_REPORT';
export const MONTHLY_REPORT = 'MONTHLY_REPORT';

export const GET_INSPECTOR = 'GET_INSPECTOR';
