export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const ADD_ROLE = 'ADD_ROLE';